[package]
name = "made"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
miette = { version = "7.2.0", features = ["fancy"] }
serde = "1.0.208"
serde_json = "1.0.125"
thiserror = "1.0.63"
